// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: register.proto

package register_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegisterV1Client is the client API for RegisterV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegisterV1Client interface {
	// Register creates a new user account
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type registerV1Client struct {
	cc grpc.ClientConnInterface
}

func NewRegisterV1Client(cc grpc.ClientConnInterface) RegisterV1Client {
	return &registerV1Client{cc}
}

func (c *registerV1Client) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/auth_v1.RegisterV1/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterV1Server is the server API for RegisterV1 service.
// All implementations must embed UnimplementedRegisterV1Server
// for forward compatibility
type RegisterV1Server interface {
	// Register creates a new user account
	Register(context.Context, *RegisterRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedRegisterV1Server()
}

// UnimplementedRegisterV1Server must be embedded to have forward compatible implementations.
type UnimplementedRegisterV1Server struct {
}

func (UnimplementedRegisterV1Server) Register(context.Context, *RegisterRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRegisterV1Server) mustEmbedUnimplementedRegisterV1Server() {}

// UnsafeRegisterV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegisterV1Server will
// result in compilation errors.
type UnsafeRegisterV1Server interface {
	mustEmbedUnimplementedRegisterV1Server()
}

func RegisterRegisterV1Server(s grpc.ServiceRegistrar, srv RegisterV1Server) {
	s.RegisterService(&RegisterV1_ServiceDesc, srv)
}

func _RegisterV1_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterV1Server).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_v1.RegisterV1/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterV1Server).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterV1_ServiceDesc is the grpc.ServiceDesc for RegisterV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegisterV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_v1.RegisterV1",
	HandlerType: (*RegisterV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _RegisterV1_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "register.proto",
}
