volumes:
  jaeger:

services:
  jaeger:
    container_name: ${COMPOSE_PROJECT_NAME}-jaeger
    image: jaegertracing/all-in-one:1.48
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" # web
      - "14268:14268"
      - "9411:9411"
    networks:
      - ${COMPOSE_NETWORK_NAME}